export const AIMEMax = 136;
export const AIMEMapping: Record<string, number[]> = {
  AOO: [17, 28, 32, 57, 101, 107, 126, 134],
  CAU: [8, 31, 38, 65, 80, 98, 100, 122],
  CPX: [6, 22, 29, 42, 67, 75, 103, 130],
  DSC: [16, 43, 60, 86, 102, 106, 110, 114],
  IMP: [4, 7, 18, 33, 82, 104, 108, 119],
  JUD: [10, 19, 30, 45, 78, 79, 95, 115],
  MNO: [3, 26, 66, 85, 94, 113, 124, 128],
  MON: [12, 21, 46, 56, 87, 90, 92, 118],
  OPN: [14, 47, 52, 58, 72, 125, 129, 136],
  PSO: [44, 48, 69, 81, 117, 121, 123, 131],
  SLA: [34, 40, 51, 84, 89, 111, 116, 120],
  SLC: [20, 25, 50, 59, 68, 73, 76, 91],
  SLE: [1, 15, 41, 64, 93, 109, 112, 133],
  SNS: [23, 54, 63, 77, 83, 88, 99, 135],
  SYM: [27, 35, 36, 39, 49, 55, 62, 74],
  THK: [2, 5, 9, 24, 70, 97, 105, 132],
  TRA: [11, 13, 37, 53, 61, 71, 96, 127]
}
export const AIMEELements: { id: string; element: string; domain: string }[] = [
  { id: "AOO", element: "Analysis of Others", domain: "Identification" },
  { id: "CAU", element: "Causes", domain: "Understand" },
  { id: "CPX", element: "Complexity", domain: "Understand" },
  { id: "DSC", element: "Discrimination", domain: "Identification" },
  { id: "IMP", element: "Impression", domain: "Impression" },
  { id: "JUD", element: "Judgment", domain: "Using" },
  { id: "MNO", element: "Managing Others", domain: "Manage" },
  { id: "MON", element: "Monitoring", domain: "Manage" },
  { id: "OPN", element: "Openness", domain: "Manage" },
  { id: "PSO", element: "Problem Solving", domain: "Using" },
  { id: "SLA", element: "Self-Analysis", domain: "Identification" },
  { id: "SLC", element: "Self-Control", domain: "Manage" },
  { id: "SLE", element: "Self-Expression", domain: "Identification" },
  { id: "SNS", element: "Sensitivity", domain: "Using" },
  { id: "SYM", element: "Symptoms", domain: "Understand" },
  { id: "THK", element: "Thinking", domain: "Using" },
  { id: "TRA", element: "Transitions", domain: "Understand" },
]
export const AIMEELement: Record<string, { element: string; domain: string }> = {
  AOO: { element: "Analysis of Others", domain: "Identification" },
  CAU: { element: "Causes", domain: "Understand" },
  CPX: { element: "Complexity", domain: "Understand" },
  DSC: { element: "Discrimination", domain: "Identification" },
  IMP: { element: "Impression", domain: "Impression" },
  JUD: { element: "Judgment", domain: "Using" },
  MNO: { element: "Managing Others", domain: "Manage" },
  MON: { element: "Monitoring", domain: "Manage" },
  OPN: { element: "Openness", domain: "Manage" },
  PSO: { element: "Problem Solving", domain: "Using" },
  SLA: { element: "Self-Analysis", domain: "Identification" },
  SLC: { element: "Self-Control", domain: "Manage" },
  SLE: { element: "Self-Expression", domain: "Identification" },
  SNS: { element: "Sensitivity", domain: "Using" },
  SYM: { element: "Symptoms", domain: "Understand" },
  THK: { element: "Thinking", domain: "Using" },
  TRA: { element: "Transitions", domain: "Understand" },
}
export const AIMELikert = {
  1: "Sangat setuju",
  2: "Setuju",
  3: "Ragu-ragu",
  4: "Tidak setuju",
  5: "Sangat tidak setuju",
}