export const fillables: Record<string, string[]> = {
  tenant: [],
  client: [],
  project: [
    'slug',
    'type',
    'title',
    'description',
    'modules',
    'criteria',
    'start_date',
    'end_date',
    'contract_date',
    'contract_value',
    'invoice_date',
    'report_lang',
    'client_contract_date',
    'client_invoice_date',
    'contact_name',
    'contact_phone',
    'contact_email',
  ],
  org_info: [
    'address1',
    'address2',
    'city',
    'province',
    'postcode',
    'phone',
    'email',
    'website',
    'org_type',
    'biz_types',
    'logo',
    'contact_name',
    'contact_phone',
    'contact_email',
    'tech_contact_name',
    'tech_contact_phone',
    'tech_contact_email',
  ],
  npwp: [
    'nomor',
    'nama',
    'nik',
    'alamat',
    'kelurahan',
    'kecamatan',
    'kota',
    'provinsi',
  ]
}